# Practical Assignment DL 00 - Solutions

##### Objective: - Predict Next Sequence
To start with deep learning, the very basic project that you can build is to predict the next digit in a sequence. 
##### Dataset:
Create a sequence like a list of odd numbers and then build a model and train it to predict the next digit in the sequence. 
##### Task:
A simple neural network with 2 layers would be sufficient to build the model.
##### Assignment Submission:
Only submit the Google Colab/Github link.(Make the Link Public).

In [56]:
import tensorflow as tf
from tensorflow import keras
import tensorflow as tf
from tensorflow.keras import layers
import numpy as np
import matplotlib.pyplot as plt

In [182]:
X = [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
y = [3, 5, 7, 9, 11, 13, 15, 17, 19, 21]
test_number = 5

X = [1, 2, 3, 4, 5, 6, 7, 8, 9]
y = [1, 2, 3, 4, 5, 6, 7, 8, 9]

In [185]:
# Set random seed
tf.random.set_seed(42)

model = keras.Sequential([
    
    keras.layers.Input(shape=(1,)),

    keras.layers.Dense(80, activation='relu'),
    #keras.layers.Dense(1, activation='relu')
    keras.layers.Dense(1, activation='softmax')
])


model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
              loss='mse',
              metrics=['mae'])

model.fit(X, y, epochs=100, verbose=0) 



In [186]:

predictions = model.predict([19])
print(predictions)

1/1 [==============================] - 0s 59ms/step
[[1.]]


In [187]:
data = [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49]
print(data)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49]


In [188]:
def splitSequence(seq, n_steps):
    X = []
    y = []
    
    for i in range(len(seq)):
        lastIndex = i + n_steps
        if lastIndex > len(seq) - 1:
            break
        seq_X, seq_y = seq[i:lastIndex], seq[lastIndex]
        X.append(seq_X)
        y.append(seq_y)
        pass
        
    X = np.array(X)
    y = np.array(y)
    
    return X,y

    pass

In [189]:
n_steps = 5
X, y = splitSequence(data, n_steps = n_steps)

In [190]:
for i in range(len(X)):
    print(X[i], y[i])

[1 3 5 7 9] 11
[ 3  5  7  9 11] 13
[ 5  7  9 11 13] 15
[ 7  9 11 13 15] 17
[ 9 11 13 15 17] 19
[11 13 15 17 19] 21
[13 15 17 19 21] 23
[15 17 19 21 23] 25
[17 19 21 23 25] 27
[19 21 23 25 27] 29
[21 23 25 27 29] 31
[23 25 27 29 31] 33
[25 27 29 31 33] 35
[27 29 31 33 35] 37
[29 31 33 35 37] 39
[31 33 35 37 39] 41
[33 35 37 39 41] 43
[35 37 39 41 43] 45
[37 39 41 43 45] 47
[39 41 43 45 47] 49


In [191]:
# reshape from [samples, timesteps] into [samples, timesteps, features]n_features = 1
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))
print(X[:2])

[[[ 1]
  [ 3]
  [ 5]
  [ 7]
  [ 9]]

 [[ 3]
  [ 5]
  [ 7]
  [ 9]
  [11]]]


In [192]:
y

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43,
       45, 47, 49])

In [194]:
# Set random seed
tf.random.set_seed(42)

model = keras.Sequential([    
    keras.layers.Input(shape=(n_steps,n_features)),   
    keras.layers.Dense(10, activation='relu'),
    keras.layers.Dense(80, activation='relu'),
    keras.layers.Dense(1, activation='relu')
])


model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
              loss='mse',
              metrics=['mae'])

model.fit(X, y, epochs=100, verbose=0) 

In [195]:
test_data = np.array([37,39,41,43,45])
test_data = test_data.reshape((1, n_steps, n_features))
predictNextNumber = model.predict(test_data, verbose=1)
print(predictNextNumber)

1/1 [==============================] - 0s 91ms/step
[[[36.40956 ]
  [38.340828]
  [40.272095]
  [42.20336 ]
  [44.13463 ]]]


In [196]:
model1 = tf.keras.Sequential()
#keras.layers.Input(shape=(1,)),
model1.add(layers.LSTM(50, activation='relu', input_shape=(n_steps,n_features)))
model1.add(layers.Dense(1))


In [197]:
model1.compile(optimizer=tf.keras.optimizers.Adam(0.01), loss=tf.keras.losses.MeanSquaredError(), metrics=['accuracy'])
model1.fit(X, y, epochs=200, verbose=0)

In [198]:
test_data = np.array([37,39,41,43,45])
test_data = test_data.reshape((1, n_steps, n_features))
predictNextNumber = model1.predict(test_data, verbose=1)
print(predictNextNumber)


1/1 [==============================] - 0s 159ms/step
[[47.10548]]
